version: '3'

services:
  hikoo-checkin:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: hikoo-checkin
    security_opt:
      - seccomp:unconfined
    container_name: hikoo-checkin
    ports:
      - "80:8080"
    hostname: hikoo-checkin